# Generated by Django 5.1.1 on 2024-09-28 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0002_alter_etape_etape_suivant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="objet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="high_level.ressource"
            ),
        ),
    ]
