# Generated by Django 5.1.1 on 2024-09-28 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0003_alter_stock_objet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="objet",
            new_name="ressource",
        ),
    ]
