# Generated by Django 5.1.1 on 2024-11-08 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0004_rename_objet_stock_ressource"),
        ("high_level", "0008_alter_etape_etape_suivant"),
    ]

    operations = []
